export const INDEX_GETGOODS_BEGTIN = 'INDEX_GETGOODS_BEGTIN'

export const INDEX_GETGOODS_END = 'INDEX_GETGOODS_END'
export const INDEX_GETGOODS = 'INDEX_GETGOODS'
export const GOODS_DETAIL = 'GOODS_DETAIL'
